class Enums:
    attributes = ['strength', 'dexterity', 'constitution', 'intelligence', 'wisdom', 'charisma']
    sizes = ['fine', 'diminutive', 'tiny', 'small', 'medium', 'large', 'huge', 'gargantuan', 'colossal']
    size_mods = [-8, -4, -2, -1, 0, 1, 2, 4, 8]
    gear_slots = ['slotless', 'armor', 'belt', 'body', 'chest', 'eyes', 'feet', 'hands', 'head', 'headband', 'neck', 'ring1', 'ring2', 'shoulder', 'wrist', 'main_hand', 'off_hand']
    bonus_types = ['armor', 'deflection', 'dodge', 'enhancement', 'natural', 'shield', 'size', 'resistance']
    ffac_types = ['armor', 'enhancement', 'natural', 'shield', 'size', 'resistance']
    touchac_types = ['deflection', 'dodge', 'size', 'resistance']
    bool_choices = ['yes', 'true', 't', '1', 'y', 'no', 'false', 'n', '0', 'f']
    weapon_damage_types = ['bludgeoning', 'piercing', 'slashing']
    energy_damage_types = ['acid', 'cold', 'electricity', 'fire', 'sonic']
